name: Website update

on:
  push:
    branches:
      - "development"

jobs:
  build:
    # ==================================================================================================================
    # Configuration.
    runs-on: ubuntu-latest

    steps:
      # ================================================================================================================
      - name: Retrieve the sources
        id: sources
        uses: actions/checkout@v2

      # ================================================================================================================
      - uses: pozetroninc/github-action-get-latest-release@master
        id: getLatestRelease
        with:
          repository: ${{ github.repository }}

      # ================================================================================================================
      - name: Change release in website sources
        id: sed
        run: find . -type f -name "*.md" -exec sed -i 's/CASSANDRE_LATEST_RELEASE/${{ steps.getLatestRelease.outputs.release }}/g' {} \;

      # ================================================================================================================
      - name: Install vuepress and build the documentation website
        run: |
          yarn add -D vuepress
          cd docs
          yarn install
          cd ..
          yarn --cwd docs build docs

      # ================================================================================================================
      - name: Deploy the documentation website
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          commit-message: "Documentation website update"
          clean: true
